pforth/csrc/sources.cmake
pforth/csrc/pf_all.h
pforth/csrc/pf_cglue.h
pforth/csrc/pf_clib.h
pforth/csrc/pf_core.h
pforth/csrc/pf_float.h
pforth/csrc/pf_guts.h
pforth/csrc/pf_host.h
pforth/csrc/pf_inc1.h
pforth/csrc/pf_io.h
pforth/csrc/pf_mem.h
pforth/csrc/pf_save.h
pforth/csrc/pf_text.h
pforth/csrc/pf_types.h
pforth/csrc/pf_win32.h
pforth/csrc/pf_words.h
pforth/csrc/pfcompfp.h
pforth/csrc/pfcompil.h
pforth/csrc/pfinnrfp.h
pforth/csrc/pforth.h
pforth/csrc/pf_cglue.c
pforth/csrc/pf_clib.c
pforth/csrc/pf_core.c
pforth/csrc/pf_inner.c
pforth/csrc/pf_io.c
pforth/csrc/pf_io_none.c
pforth/csrc/pf_mem.c
pforth/csrc/pf_save.c
pforth/csrc/pf_text.c
pforth/csrc/pf_words.c
pforth/csrc/pfcompil.c
pf_i2c.c

